# Generated by Django 4.0.4 on 2022-07-01 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('pretty_name', models.CharField(max_length=20)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('date',),
            },
        ),
        migrations.CreateModel(
            name='MatchResult',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('isresult', models.BooleanField()),
                ('datetime', models.DateTimeField()),
                ('season', models.IntegerField()),
                ('league', models.CharField(max_length=20)),
                ('h_id', models.IntegerField()),
                ('h_title', models.CharField(max_length=60)),
                ('h_short_title', models.CharField(max_length=10)),
                ('a_id', models.IntegerField()),
                ('a_title', models.CharField(max_length=60)),
                ('a_short_title', models.CharField(max_length=10)),
                ('goals_h', models.IntegerField(null=True)),
                ('goals_a', models.IntegerField(null=True)),
                ('xg_h', models.DecimalField(decimal_places=5, max_digits=7, null=True)),
                ('xg_a', models.DecimalField(decimal_places=5, max_digits=7, null=True)),
                ('forecast_w', models.DecimalField(decimal_places=5, max_digits=7, null=True)),
                ('forecast_d', models.DecimalField(decimal_places=5, max_digits=7, null=True)),
                ('forecast_l', models.DecimalField(decimal_places=5, max_digits=7, null=True)),
                ('league_link', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='result_league', to='home.league')),
            ],
            options={
                'ordering': ('-datetime',),
            },
        ),
        migrations.CreateModel(
            name='TeamHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_id', models.IntegerField()),
                ('title', models.CharField(max_length=60)),
                ('season', models.IntegerField()),
                ('league', models.CharField(max_length=20)),
                ('kolejka', models.IntegerField()),
                ('h_a', models.CharField(max_length=2)),
                ('xg', models.DecimalField(decimal_places=5, max_digits=7)),
                ('xga', models.DecimalField(decimal_places=5, max_digits=7)),
                ('npxg', models.DecimalField(decimal_places=5, max_digits=7)),
                ('npxga', models.DecimalField(decimal_places=5, max_digits=7)),
                ('deep', models.IntegerField()),
                ('deep_allowed', models.IntegerField()),
                ('scored', models.IntegerField()),
                ('missed', models.IntegerField()),
                ('xpts', models.DecimalField(decimal_places=5, max_digits=7)),
                ('result', models.CharField(max_length=2)),
                ('date', models.DateTimeField()),
                ('wins', models.IntegerField()),
                ('draws', models.IntegerField()),
                ('loses', models.IntegerField()),
                ('pts', models.IntegerField()),
                ('npxgd', models.DecimalField(decimal_places=5, max_digits=7)),
                ('ppda_att', models.IntegerField()),
                ('ppda_def', models.IntegerField()),
                ('ppda_allowed_att', models.IntegerField()),
                ('ppda_allowed_def', models.IntegerField()),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_result', to='home.matchresult')),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='SituationMatch',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('minute', models.IntegerField()),
                ('result', models.CharField(max_length=16)),
                ('x', models.DecimalField(decimal_places=5, max_digits=7)),
                ('y', models.DecimalField(decimal_places=5, max_digits=7)),
                ('xg', models.DecimalField(decimal_places=5, max_digits=7)),
                ('player', models.CharField(max_length=60)),
                ('h_a', models.CharField(max_length=2)),
                ('player_id', models.IntegerField()),
                ('situation', models.CharField(max_length=16)),
                ('shottype', models.CharField(max_length=30)),
                ('h_team', models.CharField(max_length=60)),
                ('a_team', models.CharField(max_length=60)),
                ('h_goals', models.IntegerField()),
                ('a_goals', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('player_assisted', models.CharField(max_length=60, null=True)),
                ('lastaction', models.CharField(max_length=60)),
                ('season', models.IntegerField()),
                ('match_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='situation_result', to='home.matchresult')),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='Roster',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('goals', models.IntegerField()),
                ('own_goals', models.IntegerField()),
                ('shots', models.IntegerField()),
                ('xg', models.DecimalField(decimal_places=5, max_digits=7)),
                ('time', models.IntegerField()),
                ('player_id', models.IntegerField()),
                ('team_id', models.IntegerField()),
                ('position', models.CharField(max_length=6)),
                ('player', models.CharField(max_length=60)),
                ('h_a', models.CharField(max_length=2)),
                ('yellow_card', models.IntegerField()),
                ('red_card', models.IntegerField()),
                ('roster_in', models.IntegerField()),
                ('roster_out', models.IntegerField()),
                ('key_passes', models.IntegerField()),
                ('assists', models.IntegerField()),
                ('xa', models.DecimalField(decimal_places=5, max_digits=7)),
                ('xgchain', models.DecimalField(decimal_places=5, max_digits=7)),
                ('xgbuildup', models.DecimalField(decimal_places=5, max_digits=7)),
                ('positionorder', models.IntegerField()),
                ('match_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roster_result', to='home.matchresult')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
    ]
