# Generated by Django 4.0.4 on 2022-05-19 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='matchresult',
            options={'ordering': ('-datetime',)},
        ),
        migrations.RenameField(
            model_name='teamhistory',
            old_name='match_id',
            new_name='match',
        ),
    ]
