# Generated by Django 4.0.4 on 2022-05-17 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_roster_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchresult',
            name='isresult',
            field=models.BooleanField(),
        ),
    ]
