# Generated by Django 4.0.4 on 2022-05-17 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_matchresult_isresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_id', models.IntegerField()),
                ('title', models.CharField(max_length=60)),
                ('season', models.IntegerField()),
                ('league', models.CharField(max_length=20)),
                ('kolejka', models.IntegerField()),
                ('h_a', models.CharField(max_length=2)),
                ('xg', models.DecimalField(decimal_places=5, max_digits=7)),
                ('xga', models.DecimalField(decimal_places=5, max_digits=7)),
                ('npxg', models.DecimalField(decimal_places=5, max_digits=7)),
                ('npxga', models.DecimalField(decimal_places=5, max_digits=7)),
                ('deep', models.IntegerField()),
                ('deep_allowed', models.IntegerField()),
                ('scored', models.IntegerField()),
                ('missed', models.IntegerField()),
                ('xpts', models.DecimalField(decimal_places=5, max_digits=7)),
                ('result', models.CharField(max_length=2)),
                ('date', models.DateTimeField()),
                ('wins', models.IntegerField()),
                ('draws', models.IntegerField()),
                ('loses', models.IntegerField()),
                ('pts', models.IntegerField()),
                ('npxgd', models.DecimalField(decimal_places=5, max_digits=7)),
                ('ppda_att', models.IntegerField()),
                ('ppda_def', models.IntegerField()),
                ('ppda_allowed_att', models.IntegerField()),
                ('ppda_allowed_def', models.IntegerField()),
            ],
        ),
    ]
