# Generated by Django 4.0.4 on 2022-05-19 19:15

from django.db import migrations

def link_leagues(apps, schema_editor):
    MatchResult = apps.get_model('home', 'MatchResult')
    League = apps.get_model('home', 'League')
    for match in MatchResult.objects.all():
        league, created = League.objects.get_or_create(name=match.league)
        match.league_link = league
        print(match)
        match.save()

class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_league_matchresult_league_link'),
    ]

    operations = [
        migrations.RunPython(link_leagues),
    ]
